---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Education  

- PhD Mathematics (2013) specialized in Fuzzy Topologies  
- MSc Mathematics (1995) specialized in Pure Mathematics
- BSc Mathematics and Statistics (1993)  
- Intermediate Mathematics, Statistics, Economics (1991)  

## Work Experience  

-	Wing Commander, Registrar & Data Custodian, College of Flying Training, Pakistan Air Force, Nov 15 – Jul 20   
-	Squadron Leader, Head Mathematics & Data Analytics Division, College of Aeronautical Engineering, Pakistan Air Force, Sept 2009 – Nov 2015  
-	Flight Lieutenant, College of Aeronautical Engineering, Pakistan Air Force, 1999-2004  
- Flight Lieutenant, PTTS Kohat, Pakistan Air Force, 1998-1999  


## Hobbies  
1. Ammature Astronomy  
2. Book Reading  
3. Swimming  
4. Travelling  

## Favourite Authors  
1. Bertrand Russell  
2. Will Durant  
3. Morris Kline  

## Favourite Books  
1. Sceptical Essays  
2. Mysticism and Logic  
3. Mathematical Thought from Ancient to Modern Times  
4. ادب کلچر اور مسائل از ڈاکٹر جمیل جالبی  
5. شائد، جون ایلیا  
6. A History of Mathematics by Carl B. Boyer  
